# ##############################################################################
#  Infinity. Copyright (c) 2019 Oliver Wyman Digital and Andy Wilson. This     #
#  file is subject to the terms and conditions defined in the file 'LICENSE',  #
#  which is part of this source code package.                                  #
# ##############################################################################

"""
interpret

Receives a list of score_events generated by the importscore process.
These are then turned into a list of concert_events ready to be scheduled for playing
"""
